# Generated by Django 3.0.7 on 2020-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dp', models.ImageField(default='user.png', upload_to='Portfolio', verbose_name='Profile Image')),
                ('short_description', models.TextField(verbose_name='Admin Short Description')),
                ('interests', models.TextField(verbose_name='Interests')),
                ('cv', models.FileField(max_length=500, upload_to='Portfolio', verbose_name='CV')),
                ('contact_qr', models.ImageField(upload_to='Portfolio', verbose_name='Contact QR Image')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Admin',
            },
        ),
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Admin Contact',
                'verbose_name_plural': 'Admin Contacts',
            },
        ),
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Admin Email',
                'verbose_name_plural': 'Admin Emails',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(max_length=50, verbose_name='School/College/University')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='From Date')),
                ('faculty', models.CharField(max_length=100, verbose_name='Faculty')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('per_gpa', models.CharField(max_length=50, verbose_name='Percentage or GPA')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='From Date')),
                ('worked_organization', models.CharField(max_length=100, verbose_name='Where You Worked')),
                ('short_info', models.TextField(verbose_name='Short Information About Work')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguagesAndTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.CharField(max_length=80, verbose_name='Font Awesome Iframe')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'ProgrammingLanguagesAndTools',
                'verbose_name_plural': 'ProgrammingLanguagesAndToolss',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('short_info', models.TextField(verbose_name='Short Info')),
                ('short_desc', models.TextField(verbose_name='Short Description')),
                ('project_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link to project')),
                ('hosted_on', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hosted On')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Identifier Name')),
                ('fas_iframe', models.CharField(max_length=100, verbose_name='Font Awesome Iframe Code')),
                ('link', models.CharField(max_length=500, verbose_name='Link to Website')),
            ],
            options={
                'verbose_name': 'Social Icon',
                'verbose_name_plural': 'SocialIcons',
            },
        ),
    ]
