# Generated by Django 3.0.7 on 2020-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguagesandtools',
            options={'verbose_name': 'Programming Languages And Tool', 'verbose_name_plural': 'Programming Languages And Tools'},
        ),
        migrations.AddField(
            model_name='about',
            name='address_street',
            field=models.CharField(default='a', max_length=50, verbose_name='Street Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='full_address',
            field=models.CharField(default='a', max_length=200, verbose_name='Full Address'),
            preserve_default=False,
        ),
    ]
