# Generated by Django 3.0.7 on 2020-11-05 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20201104_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincontact',
            name='number',
        ),
        migrations.AddField(
            model_name='admincontact',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{9,15}$')]),
        ),
    ]
